stages:          # List of stages for jobs, and their order of execution
  - install
  - test
  - deploy

variables:
    DEPLOY_DIR: "/home/gitlab-runner/ragbackend"
    APP_USER: "gitlab-runner"

install-job:      # This job runs in the install stage.
  stage: install
  tags:
    - ragback
  script:
    - echo "Stopping old server..."
    - if pgrep -f "uvicorn server" > /dev/null; then sudo pkill -f "uvicorn server"; else echo "No old server process found."; fi
    - echo "Creating deployment directory..."
    - sudo mkdir -p $DEPLOY_DIR
    - sudo chown -R $APP_USER:$APP_USER $DEPLOY_DIR
    - echo "Copying project files..."
    - cp -r $CI_PROJECT_DIR/* $DEPLOY_DIR/
    - echo "Creating and activating virtual environment..."
    - cd $DEPLOY_DIR
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install uv
    - uv pip install -r requirements.txt


test-job:
  stage: test
  tags:
    - ragback
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Running tests..."
    - pytest
    - echo "Tests completed."


deploy-job:
  stage: deploy
  tags:
    - ragback
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Starting new server..."
    - nohup uvicorn server:app --host 0.0.0.0 --port 8000 --reload > server.log 2>&1 &