stages:          # List of stages for jobs, and their order of execution
  # - build
  - deploy

variables:
    DEPLOY_PATH: "/home/ubuntu"



deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - ragback
  script:
    #- cd $DEPLOY_PATH
    - sudo -E /usr/bin/bash ${DEPLOY_PATH}/deploy-srv.sh


