stages:          # List of stages for jobs, and their order of execution
  - install
  - test
  - deploy
  - pyright

variables:
    DEPLOY_DIR: "/home/gitlab-runner/ragbackend"
    APP_USER: "gitlab-runner"

install-job:      # This job runs in the install stage.
  stage: install
  tags:
    - ragback
  script:
    - echo "Stopping old server..."
    - if pgrep -f "uvicorn server" > /dev/null; then sudo pkill -f "uvicorn server"; else echo "No old server process found."; fi
    - echo "Creating deployment directory..."
    - sudo mkdir -p $DEPLOY_DIR
    - sudo chown -R $APP_USER:$APP_USER $DEPLOY_DIR
    - echo "Copying project files..."
    - cp -r $CI_PROJECT_DIR/* $DEPLOY_DIR/
    - echo "Creating and activating virtual environment..."
    - cd $DEPLOY_DIR
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install uv
    - uv pip install -r requirements.txt


test-job:
  stage: test
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Running tests..."
    - pytest --cov --cov-config=coveragerc --junitxml=report.xml --cov-report term --cov-report xml:coverage.xml
    - echo "Tests completed."
    - mv report.xml $CI_PROJECT_DIR/
    - mv coverage.xml $CI_PROJECT_DIR/
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-job:
  stage: deploy
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Starting new server..."
    - nohup uvicorn server:app --host 0.0.0.0 --port 8000 --workers 4 > server.log 2>&1 &

pyright-job:
  stage: pyright
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - sudo npm install -g pyright
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Running pyright..."
    - pyright || true # pyright will return a non-zero exit code if there are errors, but we want to capture the output regardless.
    - echo "Pyright completed."