stages:          # List of stages for jobs, and their order of execution
  - backup_db
  - install
  - test
  - deploy
  - pyright

variables:
    DEPLOY_DIR: "/home/gitlab-runner/ragbackend"
    APP_USER: "gitlab-runner"

backup-job:
  stage: backup_db
  tags:
    - ragback
  script:
    - echo "Creating backup directory in container..."
    - sudo docker exec vectorsearch mkdir -p /var/lib/postgresql/data/backup
    - echo "Backing up PostgreSQL database..."
    - BACKUP_FILE=backup_$(date +%Y%m%d_%H%M%S).dump
    - export PGPASSWORD="$DB_PASS"
    - sudo docker exec -e PGPASSWORD="$DB_PASS" vectorsearch pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -F c -b -v -f /var/lib/postgresql/data/backup/$BACKUP_FILE
    - echo "Creating ~/db_backup on host..."
    - mkdir -p ~/db_backup
    - echo "Copying backup file from container to host..."
    - sudo docker cp vectorsearch:/var/lib/postgresql/data/backup/$BACKUP_FILE ~/db_backup/
    - echo "Backup completed."

install-job:      # This job runs in the install stage.
  stage: install
  tags:
    - ragback
  script:
    - echo "Stopping old server..."
    - if pgrep -f "uvicorn server" > /dev/null; then sudo pkill -f "uvicorn server"; else echo "No old server process found."; fi
    - echo "Creating deployment directory..."
    - sudo rm -rf $DEPLOY_DIR
    - sudo mkdir -p $DEPLOY_DIR
    - sudo chown -R $APP_USER:$APP_USER $DEPLOY_DIR
    - echo "Copying project files..."
    - sudo cp -r $CI_PROJECT_DIR/* $DEPLOY_DIR/
    - echo "Creating and activating virtual environment..."
    - cd $DEPLOY_DIR
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install uv
    - uv pip install -r requirements.txt
  except:
    - schedules

test-job:
  stage: test
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Running tests..."
    - pytest --cov --cov-config=coveragerc --junitxml=report.xml --cov-report term --cov-report xml:coverage.xml
    - echo "Tests completed."
    - mv report.xml $CI_PROJECT_DIR/
    - mv coverage.xml $CI_PROJECT_DIR/
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  except:
    - schedules

deploy-job:
  stage: deploy
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Checking SSL certificate and key files..."
    - '[ -f /etc/ssl/cert/key.pem ] && [ -f /etc/ssl/cert/cert.pem ] || { echo "SSL certificate or key file missing! Please place key.pem and cert.pem in /etc/ssl/cert/."; exit 1; }'
    - echo "Starting new server..."
    - nohup uvicorn server:app --host 0.0.0.0 --ssl-keyfile=/etc/ssl/cert/key.pem --ssl-certfile=/etc/ssl/cert/cert.pem --port 8000 --workers 4 > server.log 2>&1 &
  except:
    - schedules

pyright-job:
  stage: pyright
  tags:
    - ragback
  variables:
    GIT_STRATEGY: none
  script:
    - sudo npm install -g pyright
    - cd $DEPLOY_DIR
    - source .venv/bin/activate
    - echo "Running pyright..."
    - pyright || true # pyright will return a non-zero exit code if there are errors, but we want to capture the output regardless.
    - echo "Pyright completed."
  except:
    - schedules