"""chat_messages

Revision ID: 81ae8b3f2e39
Revises: 5abd77fa858a
Create Date: 2025-04-15 00:01:23.639730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ae8b3f2e39'
down_revision: Union[str, None] = '5abd77fa858a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'evaluation_records', 'evaluation_tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluation_records', type_='foreignkey')
    # ### end Alembic commands ###
