"""add used_count to knowledge_bases

Revision ID: 9ec58a187ed3
Revises: a6fe8bbde443
Create Date: 2025-06-02 21:13:11.794669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec58a187ed3'
down_revision: Union[str, None] = 'a6fe8bbde443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('used_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_index('ix_knowledge_bases_name_pgroonga', table_name='knowledge_bases', postgresql_using='pgroonga')
    op.create_index('ix_knowledge_bases_name_pgroonga', 'knowledge_bases', [sa.text('name pgroonga_text_term_search_ops_v2')], unique=False, postgresql_using='pgroonga')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_bases_name_pgroonga', table_name='knowledge_bases', postgresql_using='pgroonga')
    op.create_index('ix_knowledge_bases_name_pgroonga', 'knowledge_bases', ['name'], unique=False, postgresql_using='pgroonga')
    op.drop_column('knowledge_bases', 'used_count')
    # ### end Alembic commands ###
