"""聊天历史记录知识库id_评估数据记录是否为rag评估

Revision ID: a6f311d6a82a
Revises: 81ae8b3f2e39
Create Date: 2025-04-21 12:59:19.047736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f311d6a82a'
down_revision: Union[str, None] = '81ae8b3f2e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('knowledge_base', sa.String, nullable=True))
    op.alter_column('evaluation_tasks', 'is_rag_task',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_tasks', 'is_rag_task',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('chat_history', 'knowledge_base')
    # ### end Alembic commands ###
