"""聊天记录添加deleted列

Revision ID: b1a4b2f7ddac
Revises: a6f311d6a82a
Create Date: 2025-05-05 11:43:16.706050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a4b2f7ddac'
down_revision: Union[str, None] = 'a6f311d6a82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('deleted', sa.Boolean(), nullable=True, default=False))
    op.execute("UPDATE chat_history SET deleted = false")
    op.alter_column('chat_history', 'deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'deleted')
    # ### end Alembic commands ###
