"""知识库name的全文索引

Revision ID: cdb8ea3495d7
Revises: b1a4b2f7ddac
Create Date: 2025-05-13 19:44:51.689129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb8ea3495d7'
down_revision: Union[str, None] = 'b1a4b2f7ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
            CREATE INDEX ix_knowledge_bases_name_pgroonga
            ON knowledge_bases
            USING pgroonga (name pgroonga_text_term_search_ops_v2)
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_bases_name_pgroonga', table_name='knowledge_bases', postgresql_using='pgroonga')
    # ### end Alembic commands ###
